export const TIERS = [
  {
    name: "Silver",
    description: "Keanggotaan Awal",
    price: "Gratis",
    featured: false,
    color: "stone",
    gradient: "from-zinc-100 via-zinc-50 to-white",
    border: "border-zinc-200",
    textColor: "text-zinc-900",
    badgeVariant: "secondary",
    benefits: [
      { label: "Akun Member", included: true },
      { label: "Diskon Produk", included: true },
      { label: "Riwayat Pesanan", included: true },
      { label: "Hadiah Ulang Tahun", included: false },
      { label: "Layanan Prioritas", included: false },
    ],
  },
  {
    name: "Gold",
    description: "Pelanggan Premium",
    price: "Gratis",
    featured: false,
    color: "amber",
    gradient: "from-amber-50 via-amber-50/50 to-white",
    border: "border-amber-200",
    textColor: "text-amber-900",
    badgeVariant: "warning",
    benefits: [
      { label: "Akun Member", included: true },
      { label: "Diskon Produk", included: true },
      { label: "Riwayat Pesanan", included: true },
      { label: "Hadiah Ulang Tahun", included: true },
      { label: "Akses Awal Produk Baru", included: true },
      { label: "Layanan Prioritas", included: true },
    ],
  },
  {
    name: "Platinum",
    description: "Pelanggan VIP",
    price: "Gratis",
    featured: true,
    color: "violet",
    gradient: "from-zinc-900 via-zinc-950 to-black",
    border: "border-zinc-800",
    textColor: "text-white",
    badgeVariant: "default",
    benefits: [
      { label: "Semua Keuntungan Gold", included: true },
      { label: "Koleksi Eksklusif", included: true },
      { label: "Asisten Pribadi", included: true },
      { label: "Akses Acara Khusus", included: true },
      { label: "Reward Premium", included: true },
    ],
  },
];