export const TIERS = [
  {
    name: "Silver",
    description: "Keanggotaan awal untuk pelanggan retail fashion DM Boutiquera.",
    price: "Gratis",
    featured: false,
    color: "stone",
    gradient: "from-zinc-100 via-zinc-50 to-white",
    border: "border-zinc-200",
    textColor: "text-zinc-900",
    badgeVariant: "secondary",
    benefits: [
      { label: "Akun Member", included: true },
      { label: "Riwayat Pesanan", included: true },
      { label: "Program Loyalitas Poin Standar", included: true },
      { label: "Diskon Produk Reguler", included: true },
      { label: "Layanan Konsultasi Style Fashion", included: false },
      { label: "Request Kustom", included: false },
      { label: "Opsi Custom Size", included: false },
    ],
  },
  {
    name: "Gold",
    description: "Pelanggan Premium dengan keuntungan tambahan dan konsultasi tren.",
    price: "Gratis",
    featured: false,
    color: "amber",
    gradient: "from-amber-50 via-amber-50/50 to-white",
    border: "border-amber-200",
    textColor: "text-amber-900",
    badgeVariant: "warning",
    benefits: [
      { label: "Semua Keuntungan Silver", included: true },
      { label: "Poin Loyalitas Berlipat", included: true },
      { label: "Hadiah Ulang Tahun", included: true },
      { label: "Akses Awal Koleksi Produk Baru", included: true },
      { label: "Layanan Konsultasi Style Fashion", included: true },
      { label: "Request Kustom", included: false },
      { label: "Opsi Custom Size", included: false },
    ],
  },
  {
    name: "Platinum",
    description: "Pelanggan VIP untuk pengalaman fashion paling eksklusif dan personal.",
    price: "Gratis", // Bisa disesuaikan jika ada syarat khusus
    featured: true,
    color: "violet",
    gradient: "from-zinc-900 via-zinc-950 to-black",
    border: "border-zinc-800",
    textColor: "text-white",
    badgeVariant: "default",
    benefits: [
      { label: "Semua Keuntungan Gold", included: true },
      { label: "Akses Prioritas Koleksi Eksklusif Terbatas", included: true },
      { label: "Gratis Opsi Custom Size", included: true },
      { label: "Prioritas Permintaan Khusus", included: true },
      { label: "Asisten Pribadi", included: true },
      { label: "Styling Advice Eksklusif", included: true },
    ],
  },
];