export const TIERS = [
  {
    name: "Silver",
    description: "Entry Membership",
    price: "Free",
    featured: false,
    color: "stone",
    gradient: "from-zinc-100 via-zinc-50 to-white",
    border: "border-zinc-200",
    textColor: "text-zinc-900",
    badgeVariant: "secondary",
    benefits: [
      { label: "Member Account", included: true },
      { label: "Product Discount", included: true },
      { label: "Order History", included: true },
      { label: "Birthday Reward", included: false },
      { label: "Priority Service", included: false },
    ],
  },
  {
    name: "Gold",
    description: "Premium Customer",
    price: "Free",
    featured: false,
    color: "amber",
    gradient: "from-amber-50 via-amber-50/50 to-white",
    border: "border-amber-200",
    textColor: "text-amber-900",
    badgeVariant: "warning",
    benefits: [
      { label: "Member Account", included: true },
      { label: "Product Discount", included: true },
      { label: "Order History", included: true },
      { label: "Birthday Reward", included: true },
      { label: "Early Access Product", included: true },
      { label: "Priority Service", included: true },
    ],
  },
  {
    name: "Platinum",
    description: "VIP Customer",
    price: "Free",
    featured: true,
    color: "violet",
    gradient: "from-zinc-900 via-zinc-950 to-black",
    border: "border-zinc-800",
    textColor: "text-white",
    badgeVariant: "default",
    benefits: [
      { label: "All Gold Benefit", included: true },
      { label: "Exclusive Collection", included: true },
      { label: "Personal Assistant", included: true },
      { label: "Special Event Access", included: true },
      { label: "Premium Reward", included: true },
    ],
  },
];
